### ISSUE TITLE
install script not working 100%

### ISSUE THREAD

**Issue by andycol** [sipcapture/homer#217]
Hi Guys
after running the install script on debian 8.7 
kamailio wont start and gives the below error

loading modules under config path: //usr/lib/x86_64-linux-gnu/kamailio/modules/
loading modules under config path: //usr/lib/x86_64-linux-gnu/kamailio/modules/
 0(18534) ERROR: <core> [modparam.c:141]: set_mod_param_regex(): parameter <nonsip_hook> of type <2> not found in module <sipcapture>
 0(18534) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 108, column 40: Can't set module parameter
 0(18534) ERROR: <core> [pvapi.c:828]: pv_parse_spec2(): error searching pvar "hep"
 0(18534) ERROR: <core> [pvapi.c:1032]: pv_parse_spec2(): wrong char [0/48] in [$hep(0x00b)] at [5 (5)]
 0(18534) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 915, column 12-22: Can't get from cache: $hep(0x00b)
ERROR: bad config file (2 errors)

**Comment by adubovikov** [comment]
Can you please check the version of kamailio ? You should have kamailio 5 for new sipcapture module.

**Comment by andycol** [comment]
How can i get the newest version



version: kamailio 4.4.5 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 4.9.2

**Comment by adubovikov** [comment]
than it's wrong. The installer should install kamailio 5.

**Comment by andycol** [comment]
i used the installer and that is the one it installed
how can i fix it?

**Comment by adubovikov** [comment]
@lmangani 
looks like it still pointer to the wrong repository
https://github.com/sipcapture/homer-installer/blob/master/homer_installer.sh#L173-L174

also for Centos

**Comment by adubovikov** [comment]
@andycol as temporaly solution, please copy kamailio 4 config to your server

https://github.com/sipcapture/homer-config/blob/master/sipcapture/sipcapture.kamailio

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-installer/commit/5a75dd870e19d0681827a700b404b9a97e3bdd34

i have fixed for debian8. For centos: kamailio4

**Comment by andycol** [comment]
still get the same error

Mar 28 10:15:51 homer01 kamailio[18651]: : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 99, column 43: Can't set module par
Mar 28 10:15:51 homer01 kamailio[18651]: ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <sipcapture> found
Mar 28 10:15:51 homer01 kamailio[18651]: : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 100, column 50: Can't set module pa
Mar 28 10:15:51 homer01 kamailio[18651]: ERROR: <core> [pvapi.c:828]: pv_parse_spec2(): error searching pvar "sht"
Mar 28 10:15:51 homer01 kamailio[18651]: ERROR: <core> [pvapi.c:1032]: pv_parse_spec2(): wrong char [a/97] in [$sht(a=>method::total)] at [5 (5)]
Mar 28 10:15:51 homer01 kamailio[18651]: : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 117, column 5-26: Can't get from ca
Mar 28 10:15:51 homer01 systemd[1]: kamailio.service: control process exited, code=exited status=255
Mar 28 10:15:51 homer01 systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
-- Subject: Unit kamailio.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kamailio.service has failed.
--
-- The result is failed.

**Comment by adubovikov** [comment]
first, tell what you do? Install kamailio5 or replace config ?

**Comment by adubovikov** [comment]
please use the updated installer script.

**Comment by andycol** [comment]
can i just re-run the install script after i update it?

**Comment by andycol** [comment]
ok i updated installer and re-ran now kamailio starts

thanks will let u know of any other bugs
