### ISSUE TITLE
Call Flow order problem caused by the same timestamps in 7.7

### ISSUE THREAD

**Issue by AnouerK97** [sipcapture/homer#380]
Hello,

I am having incorrect callflow display in homer app 7.7 (tested 7.0.1 same prob), this happen when he timestamp is the same.
I am sending sip via Captagent with HEP 3 to a heplify-server 
Samee bug : https://github.com/sipcapture/homer/issues/366

**Comment by adubovikov** [comment]
the sorting should be on miliseconds, can you please share a screenshot or data that you received ?

**Comment by adubovikov** [comment]
ok, i have checked #366, really need to add USEC sorting in this case. I  will take a look

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/902d327d67ed46c5d02df6baaa0a6e26e422a7e9

it should fix the issue !

**Comment by AnouerK97** [comment]
Thank fo the reply, bu the problem still exist,
![Screenshot at Dec 13 11-25-24](https://user-images.githubusercontent.com/36081990/70793384-78150000-1d9b-11ea-954c-8e7fb38c888a.png)
![Screenshot at Dec 13 11-29-21](https://user-images.githubusercontent.com/36081990/70793670-24ef7d00-1d9c-11ea-8683-65f1af85f776.png)
![Screenshot at Dec 13 11-31-26](https://user-images.githubusercontent.com/36081990/70793671-24ef7d00-1d9c-11ea-89ad-f92032d55cde.png)

**Comment by AnouerK97** [comment]
It works thanks.

**Comment by AnouerK97** [comment]
Callflow is better now but sill some minor errors:
![Screenshot at Dec 13 13-29-24](https://user-images.githubusercontent.com/36081990/70800462-9e8f6700-1dac-11ea-838b-961a6141d8e8.png)
200 & ACK are not in the correct order

**Comment by adubovikov** [comment]
Just check the timestamps of 200 and ACK

**Comment by AnouerK97** [comment]
its the same

**Comment by adubovikov** [comment]
ok.  Looks like you have to use captagent or heplify to avoid it. We are using timestamp for sorting and we couldnt guess who should be first. I will close the issue as solved.
