### ISSUE TITLE
Home 7 No information of IP for IPv6

### ISSUE THREAD

**Issue by hamidrhashmi** [sipcapture/homer#454]
I have configured Homer7 with Freeswitch which works on IPv6. Homer displaying call like this. 

![IPv6_Flow](https://user-images.githubusercontent.com/14875110/111763125-94b7b600-88c3-11eb-98d0-c3eeef1254a6.JPG)

![IPv6_Mesages](https://user-images.githubusercontent.com/14875110/111763148-9b462d80-88c3-11eb-9fef-d315cebcd141.JPG)

and when I tried to download pcap file, it downloaded an empty file.

**Comment by lmangani** [comment]
Hi @hamidrhashmi for the flow, please use the top-right funnel menu and try Group by Port to unbundle the display.
The issue seems with parsing some of those messages. 

@AlexeyOplachko could you open an internal ticket to reproduce this in the lab?

**Comment by lmangani** [comment]
@hamidrhashmi please sync with @AlexeyOplachko to make sure this was addressed

**Comment by hamidrhashmi** [comment]
@AlexeyOplachko The issue is not fixed yet. 

VERSION: homer-app 1.3.28
VERSION: heplify-server 1.54
VERSION: FreeSWITCH version: 1.10.5-release~64bit ( 64bit) (Capture Agent)

![image](https://user-images.githubusercontent.com/14875110/129214416-3e52f5a2-f29e-458a-a641-e4e82cad3b67.png)

I made a query against the same callid in postgres DB
```
select protocol_header from hep_proto_1_call_20210812_0900 where data_header->>'callid'='e1cb848d-66f2-4f92-accb-e18400e02ac9';
```
![image](https://user-images.githubusercontent.com/14875110/129214283-aebc46fb-9624-49e2-b2fb-5ee8af197412.png)

There is no IP information in DB as well.

**Comment by adubovikov** [comment]
looks like the issue is in the old fs 1.10. To confirm that please send the HEP traffic from your fs in the pcap format or try to upgrade the fs to the latest version.
